name: Frontend Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_REPOSITORY: ${{ env.DOCKER_REGISTRY }}/{{ env.GITHUB_REPOSITORY }}
  DOCKER_TAG: ${{ env.GITHUB_SHA }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        npm install
    - name: Lint code
      run: |
        npm run lint
    - name: Run tests
      run: |
        npm run test
    - name: Create build
      run: |
        npm run build
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_TAG }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      uses: docker/push-action@v1
      with:
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_TAG }}
In this version, we set the environment variables DOCKER_REGISTRY to docker.pkg.github.com, which is 