name: Frontend Build and Deploy

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  OWNER: ${{github.repository.owner}}
  IMAGE_NAME: ${{github.repository.name}}
  TAG: $(cat VERSION)-$(echo ${{github.sha}} | tail -c 7)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install

    - name: Lint code
      run: |
        npm run lint

    - name: Run tests
      run: |
        npm run test

    - name: Create build
      run: |
        npm run build

    - name: Build Docker image
      run: |
        echo ${{env.IMAGE_NAME}}
        docker build -t ${{env.IMAGE_NAME}} .

    - name: Login to GHCR
      run: |
        echo ${{secrets.GITHUB_TOKEN}} | docker login ${{env.REGISTRY}} -u ${{env.OWNER}} --password-stdin >/dev/null 2>&1
    
    - name: Push Docker Image
      run: |
        docker tag ${{env.IMAGE_NAME}} ${{env.REGISTRY}}/${{env.OWNER}}/${{env.IMAGE_NAME}}:${{env.TAG}}
        docker push ${{env.REGISTRY}}/${{env.OWNER}}/${{env.IMAGE_NAME}}:${{env.TAG}}
