name: Frontend Build and Deploy

on:
  push:
    branches:
      - main

env: 
  IMAGE_NAME: ghcr.io/preetindersingh345/demo:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        npm install
    - name: Lint code
      run: |
        npm run lint
    - name: Run tests
      run: |
        npm run test
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA }}