name: Frontend Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ env.GITHUB_SHA }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install
    - name: Lint code
      run: |
        npm run lint
    - name: Run tests
      run: |
        npm run test
        - name: Build Docker image
      run: |
        docker build -t myimage .
    - name: Tag Docker image
      run: |
        docker tag myimage ghcr.io/myusername/myrepo:${{ env.IMAGE_TAG }}

    - name: Push Docker image
      uses: docker/push-action@v1
      with:
        tags: ghcr.io/myusername/myrepo:${{ env.IMAGE_TAG }}
