name: Frontend Build and Deploy
on:
  push:
    branches:
      - main
env:
  DOCKER_REGISTRY: hub.docker.com
  DOCKER_IMAGE: preetindersingh/github-actions
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        npm install
    - name: Lint code
      run: |
        npm run lint
    - name: Run tests
      run: |
        npm run test
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.GITHUB_SHA }}
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
      env:
        DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}