name: Frontend Build and Deploy

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  TAG: image-name
  USER: preetindersingh345
  PAT: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        npm install
    - name: Lint code
      run: |
        npm run lint
    - name: Run tests
      run: |
        npm run test
    - name: Create build
      run: |
        npm run build

    - name: Build Docker image
      run: |
        docker build -t ${{TAG}}